import React, { useMemo } from 'react';
import { BOMResult, AppSettings } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';
import { Download, RefreshCw, Layers, FileDown, Building, Calendar, FileText, TrendingUp, DollarSign, Package } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ResultsStepProps {
  bomResult: BOMResult;
  settings: AppSettings;
  onReset: () => void;
}

const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#6366F1'];

const ResultsStep: React.FC<ResultsStepProps> = ({ bomResult, settings, onReset }) => {
  const { items, metadata } = bomResult;
  
  const totalCost = useMemo(() => items.reduce((acc, item) => acc + item.amount, 0), [items]);

  const categoryData = useMemo(() => {
    const categories: Record<string, number> = {};
    items.forEach(item => {
      const cat = item.category || 'Uncategorized';
      categories[cat] = (categories[cat] || 0) + item.amount;
    });
    return Object.entries(categories)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value);
  }, [items]);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // -- PDF HEADER --
    doc.setFontSize(18);
    doc.setTextColor(41, 128, 185); // Blue
    doc.text("BILL OF MATERIALS", 14, 20);
    
    doc.setFontSize(11);
    doc.setTextColor(60);
    
    let yPos = 30;
    const lineHeight = 6;
    
    // Project Meta
    if (metadata?.projectName) {
      doc.setFont('helvetica', 'bold');
      doc.text(`Project:`, 14, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(`${metadata.projectName}`, 40, yPos);
      yPos += lineHeight;
    }
    
    if (metadata?.drawingNumber) {
      doc.setFont('helvetica', 'bold');
      doc.text(`Drawing No:`, 14, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(`${metadata.drawingNumber}`, 40, yPos);
      yPos += lineHeight;
    }
    
    if (metadata?.client) {
      doc.setFont('helvetica', 'bold');
      doc.text(`Client:`, 14, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(`${metadata.client}`, 40, yPos);
      yPos += lineHeight;
    }
    
    if (metadata?.date || metadata?.totalWeight) {
        let metaStr = "";
        if (metadata.date) metaStr += `Date: ${metadata.date}   `;
        if (metadata.totalWeight) metaStr += `Weight: ${metadata.totalWeight}`;
        doc.text(metaStr, 14, yPos);
        yPos += lineHeight;
    }

    yPos += 5;

    // -- TABLE --
    const rows = items.map(item => [
      item.category,
      item.item,
      item.description,
      item.quantity,
      item.unit,
      item.rate.toFixed(2),
      item.amount.toFixed(2)
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Category', 'Item', 'Description', 'Qty', 'Unit', 'Rate (INR)', 'Amount (INR)']],
      body: rows,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 3, valign: 'middle', lineColor: [229, 231, 235], lineWidth: 0.1 },
      alternateRowStyles: { fillColor: [249, 250, 251] },
      columnStyles: {
        0: { cellWidth: 25, fontStyle: 'bold', textColor: [100, 100, 100] }, // Category
        1: { cellWidth: 30, fontStyle: 'bold' }, // Item
        2: { cellWidth: 'auto' }, // Description
        3: { cellWidth: 15, halign: 'right' }, // Qty
        4: { cellWidth: 15 }, // Unit
        5: { cellWidth: 20, halign: 'right' }, // Rate
        6: { cellWidth: 25, halign: 'right', fontStyle: 'bold' }  // Amount
      },
    });

    // -- TOTALS --
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Estimate: ₹${totalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 14, finalY);
    
    // -- PREPARED BY --
    if (settings.businessName) {
      doc.setFontSize(10);
      doc.setTextColor(80);
      
      const pageHeight = doc.internal.pageSize.getHeight();
      let footerY = finalY + 25;
      
      if (footerY > pageHeight - 40) {
        doc.addPage();
        footerY = 40;
      }
      
      doc.setDrawColor(200);
      doc.line(14, footerY, 196, footerY);
      
      doc.text("Generated by:", 14, footerY + 8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40);
      doc.text(settings.businessName, 14, footerY + 14);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(80);
      doc.setFontSize(9);
      if (settings.businessAddress) {
        doc.text(settings.businessAddress, 14, footerY + 20);
      }
      if (settings.businessContact) {
        doc.text(`Contact: ${settings.businessContact}`, 14, footerY + 26);
      }
    }

    doc.save("AutoBOM_Estimate.pdf");
  };

  const handleDownloadCSV = () => {
    const headers = ['Category', 'Item', 'Description', 'Quantity', 'Unit', 'Rate', 'Amount'];
    const csvContent = [
      headers.join(','),
      ...items.map(item => [
        `"${item.category}"`,
        `"${item.item}"`,
        `"${item.description}"`,
        item.quantity,
        `"${item.unit}"`,
        item.rate,
        item.amount
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', 'BOM_Estimate.csv');
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  return (
    <div className="animate-fade-in max-w-6xl mx-auto space-y-8">
      
      {/* Metadata Card */}
      {metadata && (
         <div className="bg-white p-6 rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100">
           <div className="flex items-center justify-between mb-6">
             <h3 className="text-lg font-bold text-gray-800 flex items-center">
               <FileText className="mr-2 text-indigo-600" size={20} /> Project Summary
             </h3>
             <span className="text-xs font-mono bg-gray-100 text-gray-500 px-2 py-1 rounded-md">ID: {Math.random().toString(36).substr(2, 6).toUpperCase()}</span>
           </div>
           
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
             {metadata.projectName && (
               <div className="group">
                 <div className="text-xs text-gray-400 uppercase font-semibold tracking-wider mb-1 group-hover:text-indigo-500 transition-colors">Project Name</div>
                 <div className="text-base font-semibold text-gray-900">{metadata.projectName}</div>
               </div>
             )}
             {metadata.client && (
               <div className="group">
                 <div className="text-xs text-gray-400 uppercase font-semibold tracking-wider mb-1 group-hover:text-indigo-500 transition-colors">Client</div>
                 <div className="text-base font-semibold text-gray-900 flex items-center">
                   <Building size={14} className="mr-1.5 text-gray-400" /> {metadata.client}
                 </div>
               </div>
             )}
             {metadata.drawingNumber && (
               <div className="group">
                 <div className="text-xs text-gray-400 uppercase font-semibold tracking-wider mb-1 group-hover:text-indigo-500 transition-colors">Drawing No.</div>
                 <div className="text-base font-semibold text-gray-900 font-mono text-sm bg-gray-50 inline-block px-2 py-0.5 rounded border border-gray-200">{metadata.drawingNumber}</div>
               </div>
             )}
             {metadata.date && (
               <div className="group">
                 <div className="text-xs text-gray-400 uppercase font-semibold tracking-wider mb-1 group-hover:text-indigo-500 transition-colors">Date</div>
                 <div className="text-base font-semibold text-gray-900 flex items-center">
                   <Calendar size={14} className="mr-1.5 text-gray-400" /> {metadata.date}
                 </div>
               </div>
             )}
           </div>
         </div>
      )}

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-gradient-to-br from-indigo-600 to-blue-600 p-6 rounded-2xl shadow-lg shadow-blue-500/30 text-white relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <DollarSign size={80} />
          </div>
          <p className="text-blue-100 font-medium text-sm mb-1">Total Estimated Cost</p>
          <h3 className="text-3xl font-bold tracking-tight">
            ₹{totalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </h3>
          <div className="mt-4 flex items-center text-xs text-blue-100 bg-white/10 w-fit px-2 py-1 rounded-full">
            <TrendingUp size={12} className="mr-1" /> Based on supplied rates
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-md border border-gray-100 flex flex-col justify-between group hover:border-indigo-200 transition-colors">
          <div>
            <div className="flex items-center justify-between">
                <p className="text-gray-500 font-medium text-sm">Line Items</p>
                <div className="p-2 bg-purple-50 rounded-lg text-purple-600 group-hover:bg-purple-100 transition-colors">
                    <Layers size={20} />
                </div>
            </div>
            <h3 className="text-3xl font-bold text-gray-900 mt-2">
              {items.length}
            </h3>
          </div>
          <p className="text-xs text-gray-400 mt-2">Individual components identified</p>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-md border border-gray-100 flex flex-col justify-between group hover:border-indigo-200 transition-colors">
           <div>
            <div className="flex items-center justify-between">
                <p className="text-gray-500 font-medium text-sm">Total Weight</p>
                <div className="p-2 bg-orange-50 rounded-lg text-orange-600 group-hover:bg-orange-100 transition-colors">
                    <Package size={20} />
                </div>
            </div>
            <h3 className="text-3xl font-bold text-gray-900 mt-2 truncate" title={metadata?.totalWeight || 'N/A'}>
              {metadata?.totalWeight || 'N/A'}
            </h3>
          </div>
          <p className="text-xs text-gray-400 mt-2">Extracted from drawing details</p>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
        {/* Table Section */}
        <div className="xl:col-span-2 bg-white rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100 overflow-hidden flex flex-col">
          <div className="p-6 border-b border-gray-100 flex flex-wrap justify-between items-center bg-gray-50/50 gap-4">
            <h3 className="font-bold text-gray-800 text-lg">Bill of Materials</h3>
            <div className="flex space-x-3">
              <button 
                onClick={handleDownloadCSV}
                className="text-sm flex items-center text-gray-600 hover:text-blue-600 font-medium px-4 py-2 bg-white border border-gray-200 rounded-lg hover:border-blue-300 transition-all shadow-sm"
              >
                <Download size={16} className="mr-2" /> Export CSV
              </button>
              <button 
                onClick={handleDownloadPDF}
                className="text-sm flex items-center text-white bg-gray-900 hover:bg-gray-800 font-medium px-4 py-2 rounded-lg transition-all shadow-md shadow-gray-300"
              >
                <FileDown size={16} className="mr-2" /> Download PDF
              </button>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-gray-50/80 text-gray-500 text-xs uppercase tracking-wider">
                  <th className="p-5 font-semibold border-b border-gray-100">Category</th>
                  <th className="p-5 font-semibold border-b border-gray-100">Item Details</th>
                  <th className="p-5 font-semibold border-b border-gray-100 text-right">Qty</th>
                  <th className="p-5 font-semibold border-b border-gray-100 text-right">Rate</th>
                  <th className="p-5 font-semibold border-b border-gray-100 text-right">Amount</th>
                </tr>
              </thead>
              <tbody className="text-sm divide-y divide-gray-50">
                {items.map((item, idx) => (
                  <tr key={idx} className="hover:bg-blue-50/30 transition-colors group">
                    <td className="p-5 text-gray-500 font-medium whitespace-nowrap text-xs">
                        <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded border border-gray-200">
                            {item.category}
                        </span>
                    </td>
                    <td className="p-5">
                      <div className="font-bold text-gray-800 group-hover:text-blue-700 transition-colors">{item.item}</div>
                      <div className="text-gray-500 text-xs mt-1 leading-relaxed">{item.description}</div>
                    </td>
                    <td className="p-5 text-right">
                        <div className="font-medium text-gray-900">{item.quantity}</div>
                        <div className="text-gray-400 text-xs">{item.unit}</div>
                    </td>
                    <td className="p-5 text-right text-gray-600 font-mono">₹{item.rate.toFixed(2)}</td>
                    <td className="p-5 text-right font-bold text-gray-900 font-mono">₹{item.amount.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-gray-50/80 border-t border-gray-200">
                <tr>
                  <td colSpan={4} className="p-5 text-right font-bold text-gray-600 uppercase text-xs tracking-wider">Grand Total</td>
                  <td className="p-5 text-right font-bold text-2xl text-blue-600">₹{totalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        {/* Chart Section */}
        <div className="bg-white rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100 p-6 flex flex-col">
          <h3 className="font-bold text-gray-800 mb-6 text-lg">Cost Distribution</h3>
          <div className="flex-1 min-h-[350px] relative">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={categoryData}
                  cx="50%"
                  cy="50%"
                  innerRadius={80}
                  outerRadius={120}
                  paddingAngle={4}
                  dataKey="value"
                  stroke="none"
                >
                  {categoryData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip 
                  formatter={(value: number) => `₹${value.toLocaleString()}`}
                  contentStyle={{ 
                      backgroundColor: 'rgba(255, 255, 255, 0.95)', 
                      borderRadius: '12px', 
                      border: 'none', 
                      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
                      padding: '12px',
                      color: '#1f2937'
                  }}
                  itemStyle={{ fontWeight: 600, color: '#4b5563' }}
                />
                <Legend 
                    layout="horizontal" 
                    verticalAlign="bottom" 
                    align="center" 
                    wrapperStyle={{ paddingTop: '20px', fontSize: '11px', fontWeight: 500 }} 
                />
              </PieChart>
            </ResponsiveContainer>
            {/* Center Text Overlay */}
            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-[60%] text-center pointer-events-none">
                <div className="text-gray-400 text-xs font-medium uppercase tracking-wide">Total</div>
                <div className="text-xl font-bold text-gray-800">₹{(totalCost/1000).toFixed(1)}k</div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-center pt-10 pb-4">
        <button
          onClick={onReset}
          className="flex items-center space-x-2 px-8 py-3 text-gray-600 bg-white border border-gray-200 hover:bg-gray-50 hover:border-gray-300 rounded-xl font-medium transition-all shadow-sm hover:shadow-md"
        >
          <RefreshCw size={18} />
          <span>Start New Estimate</span>
        </button>
      </div>
    </div>
  );
};

export default ResultsStep;